name: run Retrieval.py
on:
  schedule:
    - cron: "0  13 * * 3"

permissions:
  contents: write

jobs:
  run-retrieval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run downloader
        run: |
          python Retrieval.py
          echo "=== ls downloads ==="
          ls -la downloads || true

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add downloads/*.xlsx downloads/*.sha256 || true
          git diff --staged --quiet || git commit -m "add/download: libraries XLSX $(date -u +'%F %T')"
          git pull --rebase origin "${{ github.ref_name }}"
          git push origin HEAD:"${{ github.ref_name }}"
